sudo: required
language: cpp

matrix:
  include:
    - compiler: g++
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
      env: COMPILER_NAME=gcc CXX=g++-7 CC=gcc-7
    - compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.8
          packages:
            - clang-3.8
      env: COMPILER=clang++-3.8

script:
  - mkdir build
  - cd build
  - cmake ..
  - make
